// The dark rehearsal, layer 1 (paid-chat plan WP-22, decision L7): whole
// purchases through the site's own routes, in process, on real SQLite, with
// the production setup of layer 2 (Click and Uzum in "test" with credentials
// generated by scripts/paid-chat/dark-rehearsal.ts, nothing live, no Telegram
// OIDC client) and one live Click run against a stub of api.click.uz.
//
//   Click: the admin's rehearsal session -> sign-in through the bot (Telegram
//   updates through the bot's webhook route, the Bot API recorded) -> an
//   order -> Prepare/Complete signed with the test secret -> the pack -> a
//   turn drawn from it -> the receipt skipped (test) -> the Seller's refund
//   record in the admin (there is no buyer refund request: WP-25) -> the pack
//   revoked. Live: the same against the stub, the receipt printed.
//   Uzum Checkout: callback -> pull; Uzum Merchant API: check -> create ->
//   confirm -> status -> reverse; each with its pack, turn and receipts.
//   Refused: a forged signature, another amount or service, a replay, two
//   Completes (and two confirms) at once, an expired order, a cookie carried
//   to another browser, a test signature on a live order.
//
// Nothing leaves the process: Telegram and the model are answered here, Click
// and Uzum by the fakes in tests/helpers; any other host throws.
// Run: node --import tsx --test tests/paid-chat-e2e-rehearsal.test.ts
import { test } from "node:test";
import assert from "node:assert/strict";
import { randomBytes, randomUUID } from "node:crypto";
import { billingFixture, liveSettings } from "./helpers/gpt-billing-fixture";
import { fakeClickMerchant } from "./helpers/click-merchant-fake";
import { uzumFixture, UZUM_FIXTURE_TEST_BASE, UZUM_FIXTURE_TEST_FISCAL } from "./helpers/uzum-fixture";
import { committedBillingSettings, siteDispatcher } from "./helpers/paid-chat-site";
import {
  adminOperator,
  Browser,
  CLICK_SECRET,
  DARK_REHEARSAL_SETTINGS,
  generateTestCredentials,
  UZUM_SECRET,
  webhookSender,
  type Answer,
  type Transport,
} from "../scripts/paid-chat/dark-rehearsal";
import { basicHeader } from "../scripts/uzum-sandbox-rehearsal";
import { signToken } from "../functions/lib/jwt";
import {
  BILLING_ORG,
  clickCredentials,
  PAID_MESSAGES,
  PRICE_TIYIN,
  type BillingEnv,
  type ClickCredentials,
} from "../functions/lib/gpt-chat/billing-config";
import { BOT_LOGIN_COOKIE } from "../functions/lib/gpt-chat/bot-login";
import { clickSignature } from "../functions/lib/gpt-chat/payment-protocol";
import { REHEARSAL_COOKIE } from "../functions/lib/gpt-chat/rehearsal";
import { fiscalizeDue } from "../functions/lib/gpt-chat/fiscal-store";
import { maintainBilling } from "../functions/lib/gpt-chat/billing-maintenance-store";
import { maintainUzum } from "../functions/lib/gpt-chat/uzum-maintenance";
import { OPENROUTER_ENDPOINT } from "../functions/lib/gpt-chat/openrouter-chat";
import { UzumStore, UZUM_MERCHANT_CONFIRM_MS, UZUM_SESSION_EXPIRED_MS } from "../functions/lib/gpt-chat/uzum-store";

const SITE = "https://gptbot.uz";
const ACCOUNT_COOKIE = "__Host-gpt_account";
const PERSON = { id: 700_400_500, language_code: "ru" };
const MIN = 60_000;
const hex = (bytes: number) => randomBytes(bytes).toString("hex");

// ── the network: Telegram and the model answered here ───────────────────────

interface BotApiCall {
  token: string;
  method: string;
  body: Record<string, any>; // eslint-disable-line @typescript-eslint/no-explicit-any -- recorded JSON
}

/** The model's answer, streamed as OpenRouter streams it. */
function streamed(text: string): Response {
  return new Response(
    `data: ${JSON.stringify({ choices: [{ delta: { content: text } }] })}\n\ndata: [DONE]\n\n`,
    { headers: { "Content-Type": "text/event-stream" } },
  );
}

/**
 * Over whatever fake is installed (Click's or Uzum's, which throw on any
 * other host): the Bot API is recorded with the token it was called with,
 * and the chat model answers.
 */
function installNetwork(): { calls: BotApiCall[]; restore: () => void } {
  const calls: BotApiCall[] = [];
  const previous = globalThis.fetch;
  globalThis.fetch = (async (input: RequestInfo | URL, init?: RequestInit) => {
    const url = new URL(input instanceof Request ? input.url : String(input));
    if (url.hostname === "api.telegram.org") {
      const [, token = "", method = ""] = /^\/bot([^/]+)\/([A-Za-z]+)$/.exec(url.pathname) ?? [];
      calls.push({ token, method, body: JSON.parse(String(init?.body ?? "{}")) });
      return Response.json({ ok: true, result: { message_id: calls.length } });
    }
    if (url.href === OPENROUTER_ENDPOINT) return streamed("Javob tayyor.");
    return previous(input, init);
  }) as typeof fetch;
  return { calls, restore: () => { globalThis.fetch = previous; } };
}

// ── the site ────────────────────────────────────────────────────────────────

type Fixture = Awaited<ReturnType<typeof billingFixture>>;

/**
 * Production: the secrets it holds (random here), the billing settings
 * committed in wrangler.toml (since runbook S2: Click live,
 * GPT_BILLING_LIVE_READY "true", Uzum off), no OIDC client, no legacy Click variables, the bot
 * @gptbotuz_bot; then `extra`, the rehearsal's or the live sale's settings.
 */
function productionLike(env: BillingEnv, extra: Partial<BillingEnv>): void {
  Object.assign(env, liveSettings(), committedBillingSettings(), {
    GPT_TELEGRAM_CLIENT_ID: "",
    GPT_TELEGRAM_CLIENT_SECRET: "",
    GPT_CLICK_TEST_SERVICE_ID: "",
    GPT_CLICK_TEST_SECRET: "",
    TELEGRAM_ASSISTANT_BOT_TOKEN: hex(20),
    TELEGRAM_ASSISTANT_WEBHOOK_SECRET: hex(16),
    OPENROUTER_API_KEY: hex(16),
    JWT_SECRET: hex(32),
  } satisfies Partial<BillingEnv>, extra);
}

/** The site's routes in process, a browser factory, the owner's admin and the recorded Bot API. */
async function harness(f: Fixture, calls: BotApiCall[]) {
  const dispatch = siteDispatcher(f.env, f.background);
  const transport: Transport = (request) => dispatch(request);
  const drain = async () => {
    while (f.background.length) await Promise.allSettled(f.background.splice(0));
  };
  const admin = adminOperator(SITE, transport, await signToken(f.env, { email: "owner@example.invalid", role: "platform_owner" }));
  let nextUpdate = 81_000;
  /** One Telegram update through the bot's webhook route, then its background work. */
  const telegram = async (update: Record<string, unknown>, updateId = nextUpdate++) => {
    const response = await dispatch(
      new Request(`${SITE}/api/telegram/assistant`, {
        method: "POST",
        headers: { "x-telegram-bot-api-secret-token": f.env.TELEGRAM_ASSISTANT_WEBHOOK_SECRET!, "Content-Type": "application/json" },
        body: JSON.stringify({ update_id: updateId, ...update }),
      }),
    );
    assert.equal(response.status, 200);
    await drain();
    return updateId;
  };
  return {
    transport,
    drain,
    admin,
    telegram,
    browser: () => new Browser(SITE, transport),
    /** First lines of what the owner's alert chat got. */
    ownerMessages: () =>
      calls.filter((c) => c.token === f.env.GPT_NOTIFY_BOT_TOKEN && c.method === "sendMessage").map((c) => String(c.body.text).split("\n")[0]),
    /** What the bot sent the person. */
    botMessages: () => calls.filter((c) => c.token === f.env.TELEGRAM_ASSISTANT_BOT_TOKEN),
  };
}
type Harness = Awaited<ReturnType<typeof harness>>;

/** merchant_prepare_id of each order Prepare accepted, for its Complete. */
const prepareIds = new Map<string, string>();
const transId = () => String(1_000_000_000 + randomBytes(3).readUIntBE(0, 3));

/** Prepare (0) or Complete (1) as Click's server sends it: a signed form, no cookie. */
async function clickCall(
  h: Harness,
  credentials: ClickCredentials,
  order: string,
  action: "0" | "1",
  over: { tx: string; prepareId?: string; amount?: string; secret?: string; serviceId?: string },
): Promise<number> {
  const p: Record<string, string> = {
    click_trans_id: over.tx,
    click_paydoc_id: String(randomBytes(4).readUInt32BE(0)),
    service_id: over.serviceId ?? credentials.serviceId,
    merchant_trans_id: order,
    amount: over.amount ?? "20000.00",
    action,
    sign_time: "2026-10-03 12:00:00",
    error: "0",
    ...(action === "1" ? { merchant_prepare_id: over.prepareId ?? "" } : {}),
  };
  const answer = await new Browser(SITE, h.transport).send("/api/payments/click", {
    form: { ...p, sign_string: clickSignature(p, over.secret ?? credentials.secretKey) },
    origin: false,
  });
  assert.equal(answer.status, 200);
  if (action === "0" && answer.body.error === 0) prepareIds.set(order, String(answer.body.merchant_prepare_id));
  return answer.body.error as number;
}

function subscribe(browser: Browser, provider: "click" | "uzum", termsVersion: unknown, locale = "ru"): Promise<Answer> {
  return browser.post("/api/gpt/subscribe", { provider, requestId: hex(16), locale, acceptTerms: true, termsVersion });
}

/** One chat turn; the reservation it left (no text is stored there). */
async function turn(h: Harness, f: Fixture, browser: Browser) {
  await browser.post("/api/gpt/chat", { message: "Salom", stream: true });
  await h.drain();
  return f.db.rows<{ period_id: string | null; status: string; charged: number | null }>(
    "SELECT period_id,status,charged FROM gpt_turn_reservations ORDER BY rowid DESC LIMIT 1",
  )[0];
}

/**
 * Sign-in through @gptbotuz_bot, first half: the site starts it, the person
 * opens the deep link (/start login_… through the webhook) and the bot asks
 * for the number. Returns the attempt and the bot's number buttons.
 */
async function openBotLink(h: Harness, browser: Browser) {
  const started = await browser.post("/api/gpt/auth/bot/start", { locale: "ru", consent: true });
  assert.equal(started.status, 200, JSON.stringify(started.body));
  assert.ok(browser.has(BOT_LOGIN_COOKIE));
  const payload = new URL(String(started.body.deepLink)).searchParams.get("start")!;
  const before = h.botMessages().length;
  const update = { message: { chat: { id: PERSON.id, type: "private" }, from: PERSON, text: `/start ${payload}` } };
  const updateId = await h.telegram(update);
  const prompts = h.botMessages().slice(before).filter((c) => c.method === "sendMessage" && c.body.chat_id === PERSON.id);
  assert.equal(prompts.length, 1);
  const numbers = ((prompts[0].body.reply_markup?.inline_keyboard ?? []) as Array<Array<{ text: string; callback_data: string }>>)
    .flat()
    .filter((key) => key.callback_data.startsWith("lg:"));
  assert.equal(numbers.length, 3);
  return { id: String(started.body.id), code: String(started.body.code), numbers, update, updateId };
}

/** Second half: the person presses the number the site shows; the browser collects the session. */
async function pressNumber(h: Harness, browser: Browser, attempt: Awaited<ReturnType<typeof openBotLink>>) {
  const right = attempt.numbers.find((key) => key.text === attempt.code);
  assert.ok(right, "the site's number is one of the bot's three");
  await h.telegram({
    callback_query: { id: `cq${hex(4)}`, from: PERSON, data: right.callback_data, message: { chat: { id: PERSON.id, type: "private" }, message_id: 77 } },
  });
  const done = await browser.post("/api/gpt/auth/bot/status", { id: attempt.id });
  assert.equal(done.body.status, "done");
  assert.ok(browser.has(ACCOUNT_COOKIE));
  assert.ok(!browser.has(BOT_LOGIN_COOKIE), "the attempt's cookie is cleared");
}

const journal = (f: Fixture, order: string) =>
  f.db.rows<{ to_state: string; actor: string; method: string }>(
    "SELECT to_state,actor,method FROM gpt_payment_journal WHERE order_id=? ORDER BY created_at,rowid",
    order,
  ).map((row) => ({ ...row }));
const periods = (f: Fixture, order: string) =>
  f.db.rows<{ revoked: number }>("SELECT revoked_at IS NOT NULL AS revoked FROM gpt_access_periods WHERE order_id=?", order).map((row) => ({ ...row }));
const receipts = (f: Fixture, order: string) =>
  f.db.rows<{ kind: string; status_code: number; last_error: string | null; receipt_url: string | null }>(
    "SELECT kind,status_code,last_error,receipt_url FROM gpt_fiscal_receipts WHERE order_id=? ORDER BY kind DESC",
    order,
  ).map((row) => ({ ...row }));
const outbox = (f: Fixture, order: string) =>
  f.db.rows<{ event: string; delivered: number }>(
    "SELECT event,delivered_at IS NOT NULL AS delivered FROM gpt_billing_outbox WHERE order_id=? ORDER BY created_at,rowid",
    order,
  ).map((row) => [row.event, row.delivered]);

/**
 * "test": exactly layer 2 (both generated secrets and DARK_REHEARSAL_SETTINGS:
 * Click and the Uzum Merchant API in test). "live": Click on sale with a live
 * block beside the test one (runbook S2).
 */
async function clickSite(t: { after: (fn: () => void) => void }, mode: "test" | "live") {
  const f = await billingFixture();
  const generated = generateTestCredentials();
  const live = { service_id: 41001, merchant_id: 32002, secret_key: hex(32), merchant_user_id: 50003 };
  productionLike(
    f.env,
    mode === "test"
      ? {
          ...DARK_REHEARSAL_SETTINGS,
          GPT_CLICK_CREDENTIALS_JSON: JSON.stringify(generated[CLICK_SECRET]),
          UZUM_CREDENTIALS_JSON: JSON.stringify(generated[UZUM_SECRET]),
        }
      : {
          GPT_BILLING_MODE_CLICK: "live",
          GPT_BILLING_LIVE_READY: "true",
          GPT_CLICK_CREDENTIALS_JSON: JSON.stringify({ live, test: generated[CLICK_SECRET].test }),
        },
  );
  const test = clickCredentials(f.env, "test")!;
  const liveCredentials = mode === "live" ? clickCredentials(f.env, "live")! : null;
  const { fake, restore } = fakeClickMerchant([
    { serviceId: test.serviceId, merchantUserId: test.merchantUserId!, secretKey: test.secretKey },
    ...(liveCredentials ? [{ serviceId: liveCredentials.serviceId, merchantUserId: liveCredentials.merchantUserId!, secretKey: liveCredentials.secretKey }] : []),
  ]);
  const network = installNetwork();
  t.after(() => {
    network.restore();
    restore();
  });
  return { f, h: await harness(f, network.calls), test, live: liveCredentials, clickFake: fake };
}

// ── Click ───────────────────────────────────────────────────────────────────

test("Click in test, start to end: rehearsal session, sign-in through the bot, Prepare/Complete with the test secret, a turn from the pack, receipt skipped, the Seller's refund record, the pack revoked", async (t) => {
  const { f, h, test: credentials, clickFake } = await clickSite(t, "test");

  // A visitor: no provider, no sign-in, no pack window, no order.
  const visitor = h.browser();
  const outside = await visitor.get("/api/gpt/account");
  assert.deepEqual([outside.status, outside.body.providers, outside.body.loginMethods, outside.body.mode], [200, [], [], null]);
  assert.equal((await visitor.post("/api/gpt/auth/bot/start", { locale: "ru", consent: true })).status, 404);
  assert.equal((await subscribe(visitor, "click", outside.body.termsVersion)).status, 404);
  assert.equal((await visitor.post("/api/gpt/event", { id: randomUUID(), type: "pack_viewed", detail: "header" })).status, 404);

  // The owner opens a rehearsal session from the admin, without a synthetic account.
  const owner = h.browser();
  const opened = await h.admin.openSession(owner, false);
  assert.equal(opened.status, 200);
  assert.deepEqual([opened.body.providers, opened.body.account], [["click", "uzum"], false]);
  assert.ok(owner.has(REHEARSAL_COOKIE) && !owner.has(ACCOUNT_COOKIE));
  const view = await owner.get("/api/gpt/account");
  assert.deepEqual(
    [view.body.mode, view.body.providers, view.body.uzumFlow, view.body.loginMethods, view.body.user],
    ["test", ["click", "uzum"], "code", ["bot"], null],
  );

  // Sign-in through the bot. Telegram retries the /start update: one question.
  const attempt = await openBotLink(h, owner);
  const asked = h.botMessages().length;
  await h.telegram(attempt.update, attempt.updateId);
  assert.equal(h.botMessages().length, asked, "a repeated update_id asks nothing again");
  // Another browser cannot collect it: without the attempt's cookie, 403;
  // with its own cookie, the attempt does not exist for it.
  const stranger = h.browser();
  await h.admin.openSession(stranger, false);
  assert.equal((await stranger.post("/api/gpt/auth/bot/status", { id: attempt.id })).status, 403);
  await stranger.post("/api/gpt/auth/bot/start", { locale: "ru", consent: true });
  assert.deepEqual((await stranger.post("/api/gpt/auth/bot/status", { id: attempt.id })).body, { ok: true, status: "expired" });
  await pressNumber(h, owner, attempt);
  assert.deepEqual((await stranger.post("/api/gpt/auth/bot/status", { id: attempt.id })).body, { ok: true, status: "expired" });
  assert.ok(!stranger.has(ACCOUNT_COOKIE));
  const signedIn = await owner.get("/api/gpt/account");
  assert.deepEqual([(signedIn.body.user as { signedIn: boolean }).signedIn, signedIn.body.access, signedIn.body.payment], [true, null, null]);

  // The order, then Click's server: Prepare, two Completes at once, a replay.
  const sub = await subscribe(owner, "click", view.body.termsVersion);
  assert.equal(sub.status, 200);
  assert.deepEqual([sub.body.mode, sub.body.amount, sub.body.currency], ["test", PRICE_TIYIN, "UZS"]);
  const order = String(sub.body.attemptId);
  const tx = transId();
  assert.equal(await clickCall(h, credentials, order, "0", { tx }), 0);
  const prepareId = prepareIds.get(order)!;
  // Both may read the order as prepared; the journal's version gate lets one write.
  const both = await Promise.all([
    clickCall(h, credentials, order, "1", { tx, prepareId }),
    clickCall(h, credentials, order, "1", { tx, prepareId }),
  ]);
  assert.ok(both.includes(0) && both.every((code) => code === 0 || code === -4), `answers ${both}`);
  assert.equal(await clickCall(h, credentials, order, "1", { tx, prepareId }), -4, "a replayed Complete: already paid");
  assert.equal(await clickCall(h, credentials, order, "0", { tx: transId() }), -4, "another Click transaction for a paid order");
  await h.drain();
  assert.deepEqual(journal(f, order).map((row) => row.to_state), ["pending", "prepared", "paid"]);
  assert.deepEqual(periods(f, order), [{ revoked: 0 }]);

  // The pack, and a turn drawn from it.
  const paid = await owner.get("/api/gpt/account");
  const access = paid.body.access as { remaining: number; packs: number };
  assert.deepEqual([(paid.body.payment as { state: string }).state, access.remaining, access.packs], ["paid", PAID_MESSAGES, 1]);
  assert.deepEqual({ ...(await turn(h, f, owner)) }, { period_id: order, status: "done", charged: 1 });
  assert.equal(((await owner.get("/api/gpt/account")).body.access as { remaining: number }).remaining, PAID_MESSAGES - 1);

  // The account cookie carried to a browser without the rehearsal cookie:
  // the live context, where no provider, test order or test pack exists.
  const carried = owner.copy([ACCOUNT_COOKIE]);
  const carriedView = await carried.get("/api/gpt/account");
  assert.deepEqual([carriedView.body.providers, carriedView.body.payment, carriedView.body.access], [[], null, null]);
  assert.equal((await subscribe(carried, "click", view.body.termsVersion)).status, 404);
  assert.equal((await turn(h, f, carried)).period_id, null, "a free turn there");

  // The receipt of a test payment is skipped; nothing reached Click.
  assert.deepEqual(receipts(f, order), [{ kind: "PERFORM", status_code: -2, last_error: "skipped_test", receipt_url: null }]);
  assert.equal((await fiscalizeDue(f.env)).printed, 0);
  assert.equal(clickFake.calls.length, 0);

  // The admin sees it as a test order with its pack.
  const row = await h.admin.paymentRow(order, "click");
  assert.ok(row);
  assert.deepEqual(
    [row.mode, row.state, row.rehearsal, row.receipt?.status, row.pack?.limit, row.pack?.used, row.pack?.revokedAt],
    ["test", "paid", false, -2, PAID_MESSAGES, 1, null],
  );

  // The Seller's refund record; a repeat changes nothing.
  const refunded = await h.admin.recordRefund(order, "rehearsal-click-1");
  assert.deepEqual([refunded.status, refunded.body.recorded], [200, true]);
  assert.deepEqual([(await h.admin.recordRefund(order, "rehearsal-click-1")).body.recorded], [false]);
  await h.drain();
  const after = await owner.get("/api/gpt/account");
  assert.deepEqual([after.body.access, (after.body.payment as { state: string }).state], [null, "refunded"]);
  assert.equal((await turn(h, f, owner)).period_id, null, "the revoked pack draws nothing");
  assert.deepEqual(periods(f, order), [{ revoked: 1 }]);
  assert.deepEqual(journal(f, order).at(-1), { to_state: "refunded", actor: "owner", method: "owner_refund_record:rehearsal-click-1" });
  const revoked = await h.admin.paymentRow(order, "click");
  assert.deepEqual([revoked?.state, typeof revoked?.pack?.revokedAt], ["refunded", "number"]);

  // The owner hears nothing of a test order: its events stay in the outbox.
  await maintainBilling(f.env);
  assert.deepEqual(outbox(f, order), [["paid", 0], ["refunded", 0]]);
  assert.equal(h.ownerMessages().filter((line) => line.includes("AI paket")).length, 0);
  // Telegram never got the order or a credential.
  const sent = JSON.stringify(h.botMessages());
  assert.ok(!sent.includes(order) && !sent.includes(credentials.secretKey));
});

test("Click in test refuses a forged signature, another amount or service, Complete before Prepare and an expired order; nothing moves", async (t) => {
  const { f, h, test: credentials } = await clickSite(t, "test");
  const owner = h.browser();
  assert.equal((await h.admin.openSession(owner, true)).status, 200);
  const terms = (await owner.get("/api/gpt/account")).body.termsVersion;
  const order = String((await subscribe(owner, "click", terms)).body.attemptId);
  const tx = transId();
  const seq = String(f.db.value("SELECT seq FROM gpt_payment_orders WHERE id=?", order));
  assert.equal(await clickCall(h, credentials, order, "0", { tx, secret: hex(32) }), -1, "forged signature");
  assert.equal(await clickCall(h, credentials, order, "0", { tx, serviceId: String(Number(credentials.serviceId) + 1) }), -1, "another service");
  assert.equal(await clickCall(h, credentials, order, "0", { tx, amount: "19999.00" }), -2, "another amount");
  assert.equal(await clickCall(h, credentials, order, "1", { tx, prepareId: seq }), -6, "Complete before Prepare");
  assert.equal(await clickCall(h, credentials, `pay_${hex(16)}`, "0", { tx }), -5, "an order that does not exist");
  assert.deepEqual(journal(f, order).map((row) => row.to_state), ["pending"]);
  assert.equal(f.db.value("SELECT state FROM gpt_payment_orders WHERE id=?", order), "pending");

  // Twelve hours later the invoice has expired: Prepare is refused, no pack.
  f.db.sqlite.prepare("UPDATE gpt_payment_orders SET expires_at=? WHERE id=?").run(Date.now() - MIN, order);
  assert.equal(await clickCall(h, credentials, order, "0", { tx }), -5, "expired");
  assert.deepEqual(periods(f, order), []);
  assert.equal(((await owner.get("/api/gpt/account")).body.payment as { state: string }).state, "cancelled");
});

test("Click live against a stub of api.click.uz: the checkout link, a test signature refused, Prepare/Complete with the live secret, the receipt printed, the owner told (never of the rehearsal's test order), the Seller's refund", async (t) => {
  const { f, h, test, live, clickFake } = await clickSite(t, "live");
  assert.ok(live);
  // The dark rehearsal's rows stay in D1 (plan WP-22): a test order paid and
  // refunded before Click went live, its events still in the outbox.
  const leftover = await f.store.createOrder(f.user, "click", "test", randomUUID());
  await f.store.transition(leftover.id, "prepared", "Prepare", { externalId: transId() });
  await f.store.transition(leftover.id, "paid", "Complete");
  await f.store.transition(leftover.id, "cancelled", "owner_refund_record:rehearsal");
  // Live is offered to everyone; a rehearsal session is not (nothing in test).
  const buyer = h.browser();
  const view = await buyer.get("/api/gpt/account");
  assert.deepEqual([view.body.mode, view.body.providers, view.body.loginMethods], ["live", ["click"], ["bot"]]);
  assert.deepEqual([(await h.admin.openSession(h.browser(), false)).status], [409]);
  await pressNumber(h, buyer, await openBotLink(h, buyer));

  const sub = await subscribe(buyer, "click", view.body.termsVersion, "uz");
  assert.equal(sub.body.mode, "checkout");
  const order = String(sub.body.attemptId);
  const link = new URL(String(sub.body.checkoutUrl));
  assert.equal(`${link.origin}${link.pathname}`, "https://my.click.uz/services/pay/");
  assert.deepEqual(Object.fromEntries(link.searchParams), {
    service_id: live.serviceId,
    merchant_id: live.merchantId,
    amount: "20000.00",
    transaction_param: order,
    return_url: `${SITE}/uz/gpt-uzbek-tilida/?pay=return`,
  });

  // The test secret never pays a live order.
  const tx = transId();
  assert.equal(await clickCall(h, test, order, "0", { tx }), -1);
  // Click's real server: it knows the payment (status_by_mti), signs with the live secret.
  const paymentId = clickFake.pay(order, Date.now(), live.serviceId);
  assert.equal(await clickCall(h, live, order, "0", { tx }), 0);
  assert.equal(await clickCall(h, live, order, "1", { tx, prepareId: prepareIds.get(order)! }), 0);
  await h.drain();

  // The receipt: printed through the queue, with the pack's codes and VAT.
  assert.deepEqual(receipts(f, order), [{ kind: "PERFORM", status_code: 0, last_error: null, receipt_url: clickFake.qrUrl(paymentId) }]);
  const [item] = clickFake.receipts.get(paymentId)!.items as Array<Record<string, unknown>>;
  assert.deepEqual(
    [item.SPIC, item.PackageCode, item.Price, item.VAT, item.VATPercent, item.CommissionInfo],
    ["10305008002000000", "1514296", PRICE_TIYIN, Math.round((PRICE_TIYIN * 12) / 112), 12, { TIN: "310618348" }],
  );
  const paid = await buyer.get("/api/gpt/account");
  assert.deepEqual(paid.body.receipts, [{ kind: "PERFORM", receipt_url: clickFake.qrUrl(paymentId) }]);
  assert.equal((paid.body.access as { remaining: number }).remaining, PAID_MESSAGES);
  assert.deepEqual({ ...(await turn(h, f, buyer)) }, { period_id: order, status: "done", charged: 1 });
  await maintainBilling(f.env);
  assert.deepEqual(h.ownerMessages().filter((line) => line.includes("AI paket")), ["GPTBot.uz · AI paket: paid"]);

  // The Seller returned the money in the Click cabinet and records it.
  assert.equal((await h.admin.recordRefund(order, "click-cabinet-1")).body.recorded, true);
  await h.drain();
  assert.equal((await buyer.get("/api/gpt/account")).body.access, null);
  assert.deepEqual(periods(f, order), [{ revoked: 1 }]);
  await maintainBilling(f.env);
  assert.deepEqual(h.ownerMessages().filter((line) => line.includes("AI paket")), ["GPTBot.uz · AI paket: paid", "GPTBot.uz · AI paket: refunded"]);
  assert.deepEqual(outbox(f, order), [["paid", 1], ["refunded", 1]]);
  // The rehearsal's test order was never announced, now that Click is live.
  assert.deepEqual(outbox(f, leftover.id), [["paid", 0], ["refunded", 0]]);
});

// ── Uzum ────────────────────────────────────────────────────────────────────

/** Uzum in test with the layer-2 setup; `api` picks Checkout or the Merchant API. */
async function uzumSite(t: { after: (fn: () => void) => void }, api: "checkout" | "merchant") {
  // autofiscal false: the receipts go through our queue to the test Fiscalization host.
  const f = await uzumFixture({ mode: "test", api, autofiscal: false });
  const generated = generateTestCredentials()[UZUM_SECRET].merchant.test;
  const packed = JSON.parse(f.env.UZUM_CREDENTIALS_JSON!) as Record<string, Record<string, unknown>>;
  productionLike(f.env, {
    GPT_BILLING_MODE_UZUM: "test",
    UZUM_API: api,
    UZUM_AUTOFISCAL: "false",
    // The Merchant API block is the one the script generates.
    UZUM_CREDENTIALS_JSON: JSON.stringify({ ...packed, merchant: { test: generated } }),
  });
  const network = installNetwork();
  t.after(() => {
    network.restore();
    f.restore();
  });
  return { f, h: await harness(f, network.calls), merchant: generated };
}

test("Uzum Checkout in test: callback -> pull, a forged callback and another amount refused, the pack and a turn, receipts on the test host, the Seller's refund only once Uzum reports it, an expired session closed", async (t) => {
  const { f, h } = await uzumSite(t, "checkout");
  // The amount mismatch below logs its alert code; that is the point of it.
  t.mock.method(console, "warn", () => undefined);
  const store = new UzumStore(f.binding, BILLING_ORG);
  const visitor = h.browser();
  assert.deepEqual((await visitor.get("/api/gpt/account")).body.providers, []);
  assert.equal((await subscribe(visitor, "uzum", "x")).status, 404);

  const owner = h.browser();
  const opened = await h.admin.openSession(owner, true);
  assert.deepEqual([opened.status, opened.body.providers, opened.body.account], [200, ["uzum"], true]);
  const view = await owner.get("/api/gpt/account");
  assert.deepEqual([view.body.mode, view.body.uzumFlow], ["test", "checkout"]);
  const sub = await subscribe(owner, "uzum", view.body.termsVersion);
  assert.equal(sub.body.mode, "checkout");
  const order = (await store.order(String(sub.body.attemptId)))!;
  // A rehearsal registers on Uzum's test terminal.
  assert.deepEqual(f.calls.map((c) => `${c.host}${c.path}`), [`${new URL(UZUM_FIXTURE_TEST_BASE).host}/api/v1/payment/register`]);
  const callback = (operationType = "COMPLETE") =>
    new Browser(SITE, h.transport).send("/api/payments/uzum", {
      json: { orderId: order.external_id, operationState: "SUCCESS", operationType, orderNumber: order.id },
      origin: false,
    });

  // The Checkout callback carries no signature: it is only a hint. While
  // Uzum's own status says otherwise, it changes nothing.
  assert.equal((await callback()).status, 200);
  assert.equal((await store.order(order.id))!.state, "prepared");
  f.settleAtUzum(order.external_id!, { status: "COMPLETED", completedAmount: PRICE_TIYIN - 100 });
  assert.equal((await callback()).status, 200);
  assert.equal((await store.order(order.id))!.state, "prepared", "another amount pays nothing");
  assert.ok(f.alerts().includes("uzum_amount_mismatch"));

  // Uzum completes: the callback, the pull, the pack. A late duplicate changes nothing.
  f.settleAtUzum(order.external_id!, { status: "COMPLETED", completedAmount: PRICE_TIYIN });
  await callback();
  await callback();
  await h.drain();
  assert.deepEqual(journal(f, order.id).map((row) => row.to_state), ["pending", "prepared", "paid"]);
  assert.equal(((await owner.get("/api/gpt/account")).body.access as { remaining: number }).remaining, PAID_MESSAGES);
  assert.deepEqual({ ...(await turn(h, f, owner)) }, { period_id: order.id, status: "done", charged: 1 });
  // The sale receipt, printed by the Fiscalization API on its test host.
  assert.equal(f.receipt(order.id).status_code, 0);
  assert.ok([...f.fiscalReceipts.values()].some((r) => r.kind === "PERFORM"));
  assert.ok(f.calls.some((c) => c.host === new URL(UZUM_FIXTURE_TEST_FISCAL).host));

  // The Seller records a refund only once Uzum itself reports it.
  const early = await h.admin.recordRefund(order.id, "uzum-cabinet-1");
  assert.deepEqual([early.status, early.body.error], [409, "not_refunded_at_uzum"]);
  assert.ok((await owner.get("/api/gpt/account")).body.access, "the pack stays until then");
  f.settleAtUzum(order.external_id!, { status: "REFUNDED", refundedAmount: PRICE_TIYIN });
  assert.equal((await h.admin.recordRefund(order.id, "uzum-cabinet-1")).body.recorded, true);
  await h.drain();
  assert.equal((await callback("REFUND")).status, 200);
  assert.equal((await owner.get("/api/gpt/account")).body.access, null);
  assert.deepEqual(periods(f, order.id), [{ revoked: 1 }]);
  assert.equal(f.receipt(order.id, "CANCEL").status_code, 0, "the refund receipt, on the test host");
  assert.equal(journal(f, order.id).filter((row) => row.to_state === "refunded").length, 1);

  // A new invoice whose Uzum session ends unpaid is closed by the maintenance tick.
  const next = (await store.order(String((await subscribe(owner, "uzum", view.body.termsVersion)).body.attemptId)))!;
  f.db.sqlite.prepare("UPDATE gpt_uzum_orders SET provider_time=provider_time-? WHERE id=?").run(UZUM_SESSION_EXPIRED_MS + MIN, next.id);
  await maintainUzum(f.env);
  assert.equal((await store.order(next.id))!.state, "cancelled");
  assert.deepEqual(periods(f, next.id), []);

  await maintainBilling(f.env);
  assert.equal(h.ownerMessages().filter((line) => line.includes("AI paket")).length, 0);
  assert.ok(outbox(f, order.id).every(([, delivered]) => delivered === 0));
});

test("Uzum Merchant API in test: check -> create -> confirm (twice at once) -> status -> reverse, every refusal, the pack and a turn, receipts on the test host, an expired transaction", async (t) => {
  const { f, h, merchant } = await uzumSite(t, "merchant");
  const store = new UzumStore(f.binding, BILLING_ORG);
  const owner = h.browser();
  assert.equal((await h.admin.openSession(owner, true)).status, 200);
  const view = await owner.get("/api/gpt/account");
  assert.equal(view.body.uzumFlow, "code");
  const issued = await subscribe(owner, "uzum", view.body.termsVersion, "uz");
  const code = String(issued.body.paymentCode);
  assert.match(code, /^[1-9]\d{8}$/);
  assert.equal((await subscribe(h.browser(), "uzum", view.body.termsVersion)).status, 404, "a visitor gets no code");

  const send = webhookSender(SITE, h.transport);
  const auth = basicHeader(merchant.login, merchant.password);
  const uzumCall = async (op: string, body: Record<string, unknown>, authorization = auth) => {
    const answer = await send(op, { serviceId: merchant.serviceId, timestamp: Date.now(), ...body }, authorization);
    return answer.status === 200 ? String(answer.body.status) : `${answer.status} ${String(answer.body.errorCode)}`;
  };
  const account = { params: { account: code } };
  const trans = randomUUID();
  assert.equal(await uzumCall("check", account, basicHeader(merchant.login, `${merchant.password}x`)), "400 10001", "a wrong password");
  assert.equal(await uzumCall("check", account), "OK");
  assert.equal(await uzumCall("create", { ...account, transId: trans, amount: PRICE_TIYIN - 100 }), "400 10011", "another amount");
  assert.equal(await uzumCall("create", { ...account, transId: trans, amount: PRICE_TIYIN }), "CREATED");
  assert.equal(await uzumCall("create", { ...account, transId: trans, amount: PRICE_TIYIN }), "400 10010", "a replayed transId");
  const confirms = await Promise.all([
    uzumCall("confirm", { transId: trans, paymentSource: "UZCARD", phone: "998900000000" }),
    uzumCall("confirm", { transId: trans, paymentSource: "UZCARD", phone: "998900000000" }),
  ]);
  assert.ok(confirms.includes("CONFIRMED") && confirms.every((s) => s === "CONFIRMED" || s === "400 10016"), `answers ${confirms}`);
  assert.equal(await uzumCall("status", { transId: trans }), "CONFIRMED");
  await h.drain();
  const order = (await store.external("test", trans))!;
  assert.deepEqual(journal(f, order.id).map((row) => row.to_state), ["pending", "prepared", "paid"]);
  assert.deepEqual(periods(f, order.id), [{ revoked: 0 }]);
  assert.equal(((await owner.get("/api/gpt/account")).body.access as { remaining: number }).remaining, PAID_MESSAGES);
  assert.deepEqual({ ...(await turn(h, f, owner)) }, { period_id: order.id, status: "done", charged: 1 });
  assert.equal(f.receipt(order.id).status_code, 0, "the sale receipt, on the test host");

  // Uzum returns the money: /reverse revokes the pack and prints the refund receipt.
  assert.equal(await uzumCall("reverse", { transId: trans }), "REVERSED");
  assert.equal(await uzumCall("reverse", { transId: trans }), "400 10018");
  await h.drain();
  assert.equal((await owner.get("/api/gpt/account")).body.access, null);
  assert.deepEqual(periods(f, order.id), [{ revoked: 1 }]);
  assert.equal(f.receipt(order.id, "CANCEL").status_code, 0);
  // The admin's record of the same refund changes nothing.
  assert.deepEqual([(await h.admin.recordRefund(order.id, "uzum-app-1")).body.recorded], [false]);

  // A transaction Uzum created but never confirmed within 30 minutes: refused, closed, no pack.
  const late = randomUUID();
  assert.equal(await uzumCall("create", { ...account, transId: late, amount: PRICE_TIYIN }), "CREATED");
  f.db.sqlite.prepare("UPDATE gpt_uzum_orders SET create_time=create_time-? WHERE external_id=?").run(UZUM_MERCHANT_CONFIRM_MS + MIN, late);
  assert.equal(await uzumCall("confirm", { transId: late, paymentSource: "HUMO", phone: "998900000000" }), "400 10015");
  assert.equal((await store.external("test", late))!.state, "cancelled");
  assert.deepEqual(periods(f, (await store.external("test", late))!.id), []);

  await maintainBilling(f.env);
  assert.equal(h.ownerMessages().filter((line) => line.includes("AI paket")).length, 0);
  assert.ok(!JSON.stringify(f.db.rows("SELECT * FROM gpt_uzum_orders")).includes("998900000000"), "the payer's phone is never stored");
});
