// functions/robots.txt.ts
//
// WHY THIS EXISTS (2026-06-25):
// The zone is on Cloudflare's Free plan, where the "Block AI bots" managed
// robots.txt feature PREPENDS a "# BEGIN Cloudflare Managed content" block to
// the statically served /robots.txt at the edge, setting `Disallow: /` for
// GPTBot, ClaudeBot, Google-Extended, Amazonbot, Bytespider, CCBot,
// meta-externalagent, Applebot-Extended + `Content-Signal: ai-train=no`.
// On the Free plan that managed block CANNOT be disabled via API (Bot
// Management API is Pro+/Enterprise only).
//
// The owner has explicitly chosen MAXIMUM AI VISIBILITY. Cloudflare's managed
// robots.txt injection only rewrites the STATIC asset response — a Pages
// Function response is generated by our own code and is NOT touched by that
// injector. So we serve /robots.txt from here, fully AI-open, verbatim.
import { buildRobotsTxt } from '../src/shared/robots-policy';

export const onRequest: PagesFunction = async () => {
  return new Response(buildRobotsTxt(), {
    status: 200,
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
      'Cache-Control': 'public, max-age=300',
      'X-Robots-Policy': 'ai-open',
      'Alt-Svc': 'clear',
    },
  });
};
