// Generates /dist/robots.txt and /dist/_redirects (Cloudflare Pages edge rules).
// Order in _redirects matters — first match wins.
//
// Layout:
//   1) /admin-tools/*       → /index.html  200   (SPA shell for admin)
//   2) <user redirects>     from content/seo/redirects.json
//   3) draft / noindex page URLs  → 410 Gone     (de-indexes phantoms)
//   4) /*                    → /index.html  200   (SPA fallback for homepage etc.)
import fs from 'node:fs';
import path from 'node:path';
import fg from 'fast-glob';
import type { Page, Redirect } from '../src/shared/types';
import { SITE_URL } from '../src/shared/site-config';
import { buildRobotsTxt } from '../src/shared/robots-policy';

const ROOT = path.resolve(import.meta.dirname, '..');
const DIST_DIR = path.join(ROOT, 'dist');
const CONTENT_DIR = path.join(ROOT, 'content');
const REDIRECTS_FILE = path.join(CONTENT_DIR, 'seo', 'redirects.json');

if (!fs.existsSync(DIST_DIR)) fs.mkdirSync(DIST_DIR, { recursive: true });

// ---------- robots.txt ----------
//
// Production AI / search policy (2026-06-24).
//
// We split crawlers into THREE classes:
//
//   (a) AI TRAINING crawlers — content used to train future models.
//       Blocked at the Cloudflare zone level via the managed
//       "Block AI Bots" feature, which PREPENDS its own section to
//       this file at the edge. We do not duplicate those rules here.
//       Examples already blocked at the edge: GPTBot (OpenAI training),
//       Google-Extended (Gemini training), ClaudeBot (Anthropic training),
//       Applebot-Extended (Apple Intelligence training), CCBot (Common
//       Crawl), Amazonbot, Bytespider, meta-externalagent.
//
//   (b) AI SEARCH / ANSWER crawlers — user-triggered retrieval for live
//       answers. We EXPLICITLY ALLOW these so GPTBot.uz can be cited and
//       linked in ChatGPT Search, Perplexity, Copilot, Claude with web
//       access, MistralAI's Le Chat, Apple Intelligence answers, etc.
//       Per each vendor's documentation, allowing the search bot does
//       NOT grant training rights (those are governed by class (a)).
//
//   (c) Traditional search crawlers — Googlebot, Bingbot, Yandex, etc.
//       Allowed via the wildcard at the bottom of the file. Yandex is
//       called out explicitly because the Uzbekistan SERP relies on it.
//
// Sensitive paths (/admin-tools/, /api/) are disallowed for ALL bots,
// including the explicit AI search agents, to keep auth UIs and admin
// JSON endpoints out of AI answer surfaces.
// robots.txt body comes from the shared single-source-of-truth module so the
// build-time file and the edge Pages Function (functions/robots.txt.ts) never
// drift. Policy: MAXIMUM AI VISIBILITY — all AI grounding/answer crawlers are
// allowed; /admin-tools/ and /api/ stay off-limits.
const robots = buildRobotsTxt(SITE_URL);
fs.writeFileSync(path.join(DIST_DIR, 'robots.txt'), robots, 'utf-8');
console.log('robots.txt → dist/robots.txt (AI-open, shared policy)');

// ---------- llms.txt static copy ----------
// /public/llms.txt is already copied to /dist/ by Vite. We add a sibling
// /llms route below (in _redirects) so the file is reachable without
// the .txt extension, matching the common "/llms" link pattern many
// LLM assistants try first.

// ---------- _redirects ----------
const userRedirects: Redirect[] = fs.existsSync(REDIRECTS_FILE)
  ? JSON.parse(fs.readFileSync(REDIRECTS_FILE, 'utf-8'))
  : [];

// Validate no loops (simple check)
const fromSet = new Set(userRedirects.map((r) => r.from));
for (const r of userRedirects) {
  if (fromSet.has(r.to)) {
    console.warn(`  ! redirect chain detected: ${r.from} → ${r.to} (target is also a redirect source)`);
  }
}

// Collect draft / noindex page URLs so phantom URLs return 410.
const pageFiles = fg.sync('pages/**/*.json', { cwd: CONTENT_DIR, absolute: true });
const pages: Page[] = pageFiles.map((f) => JSON.parse(fs.readFileSync(f, 'utf-8')));
const blogFiles = fg.sync('blog/**/*.json', { cwd: CONTENT_DIR, absolute: true });
const blogArticles = blogFiles.map((f) => JSON.parse(fs.readFileSync(f, 'utf-8'))) as { status: string; url: string; robotsIndex?: boolean }[];
const draftUrls = [
  ...pages.filter((p) => p.status === 'draft' || p.status === 'noindex' || p.robotsIndex === false).map((p) => p.url),
  ...blogArticles.filter((a) => a.status === 'draft' || a.status === 'noindex' || a.robotsIndex === false).map((a) => a.url),
].filter((u) => u && u !== '/');

const lines: string[] = [];
lines.push('# Generated by generate-robots.ts — DO NOT EDIT directly.');
lines.push('# Source: content/seo/redirects.json + draft pages list.');
lines.push('');
// 0) Canonical host: force www → non-www (SEO audit flagged both serving 200,
//    causing a www/non-www duplicate-content split). 301 consolidates all
//    ranking signal onto https://gptbot.uz. Must be first so it wins.
lines.push('# 0) Canonical host — www → non-www (301)');
lines.push('https://www.gptbot.uz/*  https://gptbot.uz/:splat  301');
lines.push('');
lines.push('# 1) Admin SPA');
lines.push('/admin-tools/*  /index.html  200');
lines.push('');
lines.push('# 1b) /llms (no extension) — rewrite to /llms.txt so AI assistants');
lines.push('#     that probe for the bare path get the same llms.txt grounding file.');
lines.push('/llms  /llms.txt  200');
lines.push('');
if (userRedirects.length) {
  lines.push('# 2) User-defined redirects (content/seo/redirects.json)');
  for (const r of userRedirects) lines.push(`${r.from}  ${r.to}  ${r.statusCode}`);
  lines.push('');
}
if (draftUrls.length) {
  lines.push('# 3) Draft / noindex pages — return 404 (Cloudflare Pages does NOT support 410 in _redirects).');
  lines.push('#    404 has the same de-indexing effect for Google as 410 over time, and the served');
  lines.push('#    404.html carries a noindex,nofollow meta so any phantom indexing is purged.');
  for (const u of draftUrls) lines.push(`${u}  /404.html  404`);
  lines.push('');
}
// NOTE: NO wildcard `/*  /index.html  200` fallback.
// Without it AND with a /404.html present in the build output, Cloudflare Pages
// will automatically serve /404.html with HTTP 404 for any unknown URL.
// This prevents random/typo URLs from serving the homepage SPA shell and
// being treated as soft-duplicates / "Crawled - currently not indexed" in GSC.
lines.push('# 4) No SPA wildcard fallback by design: unknown URLs must return 404.');
lines.push('#    The only client-rendered route is /admin-tools/* (handled above).');
lines.push('#    Cloudflare Pages auto-serves /404.html (HTTP 404) for unmatched paths.');

fs.writeFileSync(path.join(DIST_DIR, '_redirects'), lines.join('\n') + '\n', 'utf-8');
console.log(`_redirects → dist/_redirects (${userRedirects.length} user redirects, ${draftUrls.length} draft 410s)`);

// ---------- _headers ----------
// Cloudflare Pages reads this file and applies the headers at the edge.
// Order matters; first match wins. We use it to:
//   1. Force `Alt-Svc: clear` everywhere so the browser FORGETS the cached
//      HTTP/3 / QUIC advertisement that was causing ERR_QUIC_PROTOCOL_ERROR
//      after HTTP/3 was disabled at the zone level. Without this, Chrome
//      keeps retrying the broken QUIC session it has in its Alt-Svc cache
//      until it expires (~7 days).
//   2. Admin SPA shell (`/admin-tools/*`) and HTML entry points are
//      `Cache-Control: no-store, must-revalidate` so the SPA never serves
//      a stale shell after a deploy.
//   3. Hashed Vite assets (`/assets/*`) get `immutable` long-cache (1 year).
//   4. JSON SEO files (sitemap, robots) get a short cache so cron picks up
//      changes fast.
//   5. Strong security headers (X-Content-Type-Options, Referrer-Policy,
//      Permissions-Policy, X-Frame-Options) on the admin shell.
const headers: string[] = [];
headers.push('# Generated by generate-robots.ts — DO NOT EDIT directly.');
headers.push('');
headers.push('# ─── Global: kill cached QUIC / HTTP-3 advertisements ───');
headers.push('# Browsers (Chrome, Edge) cache the Alt-Svc header for up to 7 days');
headers.push('# and will keep trying HTTP/3 even after the zone disables it,');
headers.push('# producing ERR_QUIC_PROTOCOL_ERROR. Alt-Svc: clear flushes that');
headers.push('# cache on the first response over HTTP/2.');
headers.push('/*');
headers.push('  Alt-Svc: clear');
headers.push('  X-Content-Type-Options: nosniff');
headers.push('  Referrer-Policy: strict-origin-when-cross-origin');
headers.push('  Permissions-Policy: geolocation=(), microphone=(), camera=(), payment=()');
// ─── Security baseline added 2026-06-26 (SEO audit: 60 critical findings) ───
// HSTS forces HTTPS for 1 year (+ preload-eligible). X-Frame-Options +
// frame-ancestors block clickjacking on EVERY page (previously only the admin
// shell). CSP ships in Report-Only first so it cannot break the live site — it
// only collects violation reports. Promote to enforcing
// `Content-Security-Policy` once reports are verified clean.
headers.push('  Strict-Transport-Security: max-age=31536000; includeSubDomains; preload');
headers.push('  X-Frame-Options: SAMEORIGIN');
headers.push('  Cross-Origin-Opener-Policy: same-origin');
headers.push("  Content-Security-Policy-Report-Only: default-src 'self'; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://www.google-analytics.com https://connect.facebook.net https://analytics.ahrefs.com https://challenges.cloudflare.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com data:; img-src 'self' data: https: blob:; connect-src 'self' https://www.google-analytics.com https://region1.google-analytics.com https://analytics.ahrefs.com https://connect.facebook.net https://www.facebook.com; frame-src 'self' https://www.googletagmanager.com https://td.doubleclick.net https://challenges.cloudflare.com; frame-ancestors 'self'; base-uri 'self'; form-action 'self'; object-src 'none'; upgrade-insecure-requests");
headers.push('');

headers.push('# ─── Admin SPA — never cache the shell ───');
headers.push('# `must-revalidate` + `no-store` guarantees that every reload');
headers.push('# of /admin-tools/* fetches a fresh index.html, so a deploy is');
headers.push('# visible immediately and CF Pages edge cache cannot serve a');
headers.push('# stale shell that references already-deleted /assets/*.js.');
headers.push('/admin-tools/*');
headers.push('  Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
headers.push('  Pragma: no-cache');
headers.push('  Expires: 0');
headers.push('  X-Frame-Options: DENY');
headers.push('  X-Robots-Tag: noindex, nofollow');
headers.push('  Alt-Svc: clear');
headers.push('');

headers.push('# ─── Hashed Vite assets — immutable 1-year cache ───');
headers.push('# Vite emits content-hashed filenames in /assets, so the same URL');
headers.push('# never changes content. Safe to cache forever.');
headers.push('/assets/*');
headers.push('  Cache-Control: public, max-age=31536000, immutable');
headers.push('');

headers.push('# ─── SEO files — short cache ───');
headers.push('/sitemap.xml');
headers.push('  Cache-Control: public, max-age=300');
headers.push('  Content-Type: application/xml; charset=utf-8');
headers.push('/robots.txt');
headers.push('  Cache-Control: public, max-age=300');
headers.push('/llms.txt');
headers.push('  Cache-Control: public, max-age=21600');
headers.push('  Content-Type: text/plain; charset=utf-8');
headers.push('/_redirects');
headers.push('  Cache-Control: no-store');
headers.push('');

headers.push('# ─── API responses must never be cached at the edge ───');
headers.push('# (defence in depth — the Functions code also sets these).');
headers.push('/api/*');
headers.push('  Cache-Control: no-store, no-cache, must-revalidate');
headers.push('  Alt-Svc: clear');
headers.push('');

fs.writeFileSync(path.join(DIST_DIR, '_headers'), headers.join('\n') + '\n', 'utf-8');
console.log(`_headers → dist/_headers (Alt-Svc: clear globally; admin no-store; /assets/* immutable)`);

// Also propagate _routes.json from /public if present
const routesSrc = path.join(ROOT, 'public', '_routes.json');
const routesDst = path.join(DIST_DIR, '_routes.json');
if (fs.existsSync(routesSrc) && !fs.existsSync(routesDst)) {
  fs.copyFileSync(routesSrc, routesDst);
  console.log('_routes.json → dist/_routes.json');
}
