// Generates /dist/robots.txt and /dist/_redirects (Cloudflare Pages edge rules).
// Order in _redirects matters — first match wins.
//
// Layout:
//   1) /admin-tools/*       → /index.html  200   (SPA shell for admin)
//   2) <user redirects>     from content/seo/redirects.json
//   3) draft / noindex page URLs  → 410 Gone     (de-indexes phantoms)
//   4) /*                    → /index.html  200   (SPA fallback for homepage etc.)
import fs from 'node:fs';
import path from 'node:path';
import fg from 'fast-glob';
import type { Page, Redirect } from '../src/shared/types';
import { SITE_URL } from '../src/shared/site-config';

const ROOT = path.resolve(import.meta.dirname, '..');
const DIST_DIR = path.join(ROOT, 'dist');
const CONTENT_DIR = path.join(ROOT, 'content');
const REDIRECTS_FILE = path.join(CONTENT_DIR, 'seo', 'redirects.json');

if (!fs.existsSync(DIST_DIR)) fs.mkdirSync(DIST_DIR, { recursive: true });

// ---------- robots.txt ----------
const robots = `User-agent: *
Allow: /
Disallow: /admin-tools/
Disallow: /api/

Sitemap: ${SITE_URL}/sitemap.xml
`;
fs.writeFileSync(path.join(DIST_DIR, 'robots.txt'), robots, 'utf-8');
console.log('robots.txt → dist/robots.txt');

// ---------- _redirects ----------
const userRedirects: Redirect[] = fs.existsSync(REDIRECTS_FILE)
  ? JSON.parse(fs.readFileSync(REDIRECTS_FILE, 'utf-8'))
  : [];

// Validate no loops (simple check)
const fromSet = new Set(userRedirects.map((r) => r.from));
for (const r of userRedirects) {
  if (fromSet.has(r.to)) {
    console.warn(`  ! redirect chain detected: ${r.from} → ${r.to} (target is also a redirect source)`);
  }
}

// Collect draft / noindex page URLs so phantom URLs return 410.
const pageFiles = fg.sync('pages/**/*.json', { cwd: CONTENT_DIR, absolute: true });
const pages: Page[] = pageFiles.map((f) => JSON.parse(fs.readFileSync(f, 'utf-8')));
const blogFiles = fg.sync('blog/**/*.json', { cwd: CONTENT_DIR, absolute: true });
const blogArticles = blogFiles.map((f) => JSON.parse(fs.readFileSync(f, 'utf-8'))) as { status: string; url: string; robotsIndex?: boolean }[];
const draftUrls = [
  ...pages.filter((p) => p.status === 'draft' || p.status === 'noindex' || p.robotsIndex === false).map((p) => p.url),
  ...blogArticles.filter((a) => a.status === 'draft' || a.status === 'noindex' || a.robotsIndex === false).map((a) => a.url),
].filter((u) => u && u !== '/');

const lines: string[] = [];
lines.push('# Generated by generate-robots.ts — DO NOT EDIT directly.');
lines.push('# Source: content/seo/redirects.json + draft pages list.');
lines.push('');
lines.push('# 1) Admin SPA');
lines.push('/admin-tools/*  /index.html  200');
lines.push('');
if (userRedirects.length) {
  lines.push('# 2) User-defined redirects (content/seo/redirects.json)');
  for (const r of userRedirects) lines.push(`${r.from}  ${r.to}  ${r.statusCode}`);
  lines.push('');
}
if (draftUrls.length) {
  lines.push('# 3) Draft / noindex pages — return 410 Gone so search engines purge any phantom indexing.');
  for (const u of draftUrls) lines.push(`${u}  /  410`);
  lines.push('');
}
lines.push('# 4) SPA fallback (must be LAST). Prerendered static HTML files are served first.');
lines.push('/*  /index.html  200');

fs.writeFileSync(path.join(DIST_DIR, '_redirects'), lines.join('\n') + '\n', 'utf-8');
console.log(`_redirects → dist/_redirects (${userRedirects.length} user redirects, ${draftUrls.length} draft 410s)`);

// Also propagate _routes.json from /public if present
const routesSrc = path.join(ROOT, 'public', '_routes.json');
const routesDst = path.join(DIST_DIR, '_routes.json');
if (fs.existsSync(routesSrc) && !fs.existsSync(routesDst)) {
  fs.copyFileSync(routesSrc, routesDst);
  console.log('_routes.json → dist/_routes.json');
}
