// Shared AI SEO Autopilot types — used by admin SPA, Cloudflare Functions, and test scripts.
//
// Architecture (P0 MVP):
//   - Puter Free LLM = primary provider (browser-side, no API key)
//   - Mock provider  = offline / tests
//   - Gemini Free    = optional backend fallback (P1; only if GEMINI_API_KEY set)
//   - OpenRouter is NOT used.
//
// Hard rules:
//   - AI generates patches only; never auto-publish.
//   - Backend validates every patch field.
//   - Admin approves fields one-by-one.
//   - Approved fields apply only to a local AI-runs ledger; published JSON
//     under content/pages/** and content/blog/** is never touched by AI.

import type { Locale } from './types';

export type AiProvider = 'puter' | 'gemini' | 'mock';

export type AiProviderAvailability = 'available' | 'loading' | 'missing' | 'failed';

export interface AiProviderStatus {
  provider: AiProvider;
  availability: AiProviderAvailability;
  /** Optional model id discovered at runtime (Puter.listModels, etc). */
  model?: string;
  /** Short human-readable explanation. Never includes secrets. */
  note?: string;
}

export type AiSeoAction =
  | 'fix_orphan_article'
  | 'improve_article_seo'
  | 'add_internal_links'
  | 'add_related_to_money_page'
  | 'cannibalization_fix'
  | 'topic_cluster_backfill'
  | 'freshness_refresh';

export type AiSeoRisk = 'low' | 'medium' | 'high';

export type AiPatchFieldKey =
  | 'title'
  | 'description'
  | 'h1'
  | 'heroSubtitle'
  | 'intro'
  | 'topicCluster'
  | 'targetMoneyPage'
  | 'faq'
  | 'internalLinks'
  | 'keywords'
  | 'ogTitle'
  | 'ogDescription';

/** A single field-level change proposed by the LLM. */
export interface AiSeoPatchField {
  /** Stable id so UI can accept/reject individual fields. */
  id: string;
  field: AiPatchFieldKey;
  before: unknown;
  after: unknown;
  reason: string;
  risk: AiSeoRisk;
  /** Backend-only: filled in by validate-patch. */
  warnings?: string[];
  /** Backend-only: true → blocked, must not be approvable. */
  blocked?: boolean;
  /** Backend-only: human-readable why this is blocked. */
  blockReason?: string;
}

/** Full candidate patch generated by an LLM. */
export interface AiSeoPatchCandidate {
  url: string;
  locale: Locale;
  action: AiSeoAction;
  provider: AiProvider;
  model?: string;
  /** Field-level diff (slugs/canonicals are NOT a field — they cannot change). */
  fields: AiSeoPatchField[];
  /** Optional summary the LLM produced. Backend trims/sanitizes. */
  summary?: string;
  requiresHumanReview?: boolean;
  /** Raw text from provider, kept only in-memory for debug; never persisted. */
  rawText?: string;
}

/** Server-validated patch (what UI renders + admin approves). */
export interface AiSeoPatch extends AiSeoPatchCandidate {
  runId: string;
  validatedAt: string; // ISO
  /** Patch-level blockers (e.g. URL not in content store) — block the whole patch. */
  globalErrors: string[];
  /** Patch-level warnings the admin should see but not blocking. */
  globalWarnings: string[];
  /** True → patch is safe to display. Even safe patches require per-field approval. */
  acceptable: boolean;
}

export interface AiSeoValidationReport {
  patch: AiSeoPatch;
}

export type AiSeoRunStatus =
  | 'generated'
  | 'validated'
  | 'applied'
  | 'rejected'
  | 'error';

export interface AiSeoRunLog {
  runId: string;
  url: string;
  action: AiSeoAction;
  provider: AiProvider;
  model?: string;
  status: AiSeoRunStatus;
  approvedFields: AiPatchFieldKey[];
  errors: string[];
  createdAt: string;
  /** Snapshot of approved field values applied to admin ai-runs ledger. */
  applied?: Partial<Record<AiPatchFieldKey, unknown>>;
}

/** Compact context the frontend sends to the LLM so prompts stay <2k tokens. */
export interface AiPatchContext {
  url: string;
  locale: Locale;
  kind: 'page' | 'blog';
  pageType: string;
  primaryKeyword: string;
  title: string;
  description: string;
  h1: string;
  heroSubtitle?: string;
  intro?: string;
  faqQ: string[];
  internalTargets: string[]; // already-linked targets
  topicCluster?: string;
  targetMoneyPage?: string;
  /** allowedSlugs = full URLs that exist in content store (for internal link suggestions) */
  allowedSlugs: string[];
  /** Sibling articles in same locale + cluster (for orphan / related). */
  clusterPeers: { url: string; title: string }[];
  /** Money URLs in same cluster (for orphan → money linking). */
  clusterMoneyUrls: string[];
  /** SERP digest — P1 (Serper integration). Empty for now. */
  serpDigest?: {
    intent?: string;
    topCompetitorTitles?: string[];
    relatedSearches?: string[];
    faqIdeas?: string[];
    contentGaps?: string[];
  };
}

export const AI_SEO_ACTIONS: AiSeoAction[] = [
  'fix_orphan_article',
  'improve_article_seo',
  'add_internal_links',
  'topic_cluster_backfill',
];

/** Used by UI labels — keep human-readable. */
export const AI_SEO_ACTION_LABELS: Record<AiSeoAction, string> = {
  fix_orphan_article: 'Fix orphan article',
  improve_article_seo: 'Improve article SEO',
  add_internal_links: 'Add internal links',
  add_related_to_money_page: 'Add related to money page',
  cannibalization_fix: 'Cannibalization fix',
  topic_cluster_backfill: 'Backfill topicCluster',
  freshness_refresh: 'Refresh stale article',
};
